on:
  pull_request: {}
  push: {}

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "24.13.0"
      - uses: actions/checkout@v4
      - run: npm clean-install
      - run: npm run formatting

  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "24.13.0"
      - uses: actions/checkout@v4
      - run: npm clean-install
      - run: npm run spelling
