on:
  pull_request: {}
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "24.13.0"
      - uses: actions/checkout@v4
      - run: npm clean-install
      - run: npm run tsc
      - run: npm test

  test-sbe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "24.13.0"
      - uses: actions/checkout@v4
      - run: npm clean-install
      - run: npm run tsc
      - run: npm run test-sbe

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "24.13.0"
      - uses: actions/checkout@v4
      - run: npm clean-install
      - run: npm run tsc
      - run: npm run coverage
      - uses: actions/upload-artifact@v4
        with:
          name: lcov-report
          path: coverage/lcov-report/**
